version: "3.9"

services:
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:latest
    ports:
      - 8080:8080
      - 50051:50051
      - 2112:2112
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 40 #maximum number of objects Weaviate returns for a query
      ENABLE_MODULES: "backup-s3,text2vec-openai"
      ENABLE_API_BASED_MODULES: "true"
      
      CLUSTER_HOSTNAME: "node1"

      ## Monitoring configuration
      PROMETHEUS_MONITORING_ENABLED: "true"
      PROMETHEUS_MONITORING_PORT: 2112  #defaultexpose the metrics at <hostname>:2112/metrics

      ## authentication configuration
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "false"
      AUTHENTICATION_APIKEY_ENABLED: "true"
      AUTHENTICATION_APIKEY_ALLOWED_KEYS: "jbc_admin,jbc_dev"
      AUTHENTICATION_APIKEY_USERS: "admin,user"


      ## backup configuration
      # ENABLE_MODULES: "backup-filesystem" # Enable the filesystem backup module
      # BACKUP_FILESYSTEM_PATH: "/var/lib/weaviate/backups" # Set backup location (e.g. within a Docker container or on a Kubernetes pod)

      ## s3 backup configuration
      BACKUP_S3_ENDPOINT: s3.amazonaws.com
      BACKUP_S3_BUCKET: sevensix-weaviate #vectordb.backup
      BACKUP_S3_PATH: dev
      BACKUP_S3_REGION: ap-northeast-1
      # AWS credentials from .env
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}

      PERSISTENCE_DATA_PATH: "/var/lib/weaviate" #storage location inside the container

      DISABLE_TELEMETRY: "true" # Disable telemetry to avoid data being sent to Weaviate

    depends_on:
      - postgres
    volumes:
      - ./weaviate:/var/lib/weaviate #to store the data on the local machine

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: sevensix_dev_1
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    # command: ["postgres", "-c", "max_connections=200"]
    command: >
      postgres -c logging_collector=on
             -c max_connections=200
             -c log_directory=/var/lib/postgresql/data/log
             -c log_filename=postgresql.log
             -c log_connections=on
             -c log_disconnections=on
             -c log_duration=on
             -c log_min_messages=info

  pgbouncer:
    image: edoburu/pgbouncer:latest
    container_name: pgbouncer
    restart: always
    depends_on:
      - postgres
    ports:
      - "6432:6432"
    environment:
      DATABASE_URL: postgres://postgres:2244@postgres:5432/sevensix_dev_1
      POOL_MODE: transaction   # or session
      MAX_CLIENT_CONN: 1000    # max client connections allowed to PgBouncer
      DEFAULT_POOL_SIZE: 20    # actual connections PgBouncer keeps to Postgres
    volumes:
      - ./pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ./userlist.txt:/etc/pgbouncer/userlist.txt
      - ./pgbouncer.log:/var/log/pgbouncer/pgbouncer.log

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      - weaviate

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  weaviate_data:
  postgres_data:
  grafana_data: